/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hoytsmarkplanet.view;

import com.mycompany.hoytsmarkplanet.controller.ConectorDB;
import com.mycompany.hoytsmarkplanet.controller.PeliculaController;
import com.mycompany.hoytsmarkplanet.model.PeliculaDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sjeld
 */
public class AgregarPelicula extends javax.swing.JFrame {

    /**
     * Creates new form AgregarPelicula
     */
    public AgregarPelicula() throws SQLException {
        initComponents();
        this.conector = new ConectorDB();
        this.conector.crearConexion();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1ID = new javax.swing.JLabel();
        jLabel2Titulo = new javax.swing.JLabel();
        jLabel3Director = new javax.swing.JLabel();
        jLabel4Año = new javax.swing.JLabel();
        jLabel5Duracion = new javax.swing.JLabel();
        jLabel6Genero = new javax.swing.JLabel();
        jButton1Limpiar = new javax.swing.JButton();
        jButton1Agregar = new javax.swing.JButton();
        jTextField1ID = new javax.swing.JTextField();
        jTextField1Titulo = new javax.swing.JTextField();
        jTextField1Director = new javax.swing.JTextField();
        jTextField1Año = new javax.swing.JTextField();
        jTextField1Duracion = new javax.swing.JTextField();
        jTextField1Genero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1ID.setText("ID");

        jLabel2Titulo.setText("Titulo");

        jLabel3Director.setText("Director");

        jLabel4Año.setText("Año");

        jLabel5Duracion.setText("Duracion");

        jLabel6Genero.setText("Genero");

        jButton1Limpiar.setText("Limpiar");
        jButton1Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1LimpiarActionPerformed(evt);
            }
        });

        jButton1Agregar.setText("Agregar");
        jButton1Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1AgregarActionPerformed(evt);
            }
        });

        jTextField1ID.setColumns(10);

        jTextField1Titulo.setColumns(10);

        jTextField1Director.setColumns(10);

        jTextField1Año.setColumns(10);

        jTextField1Duracion.setColumns(10);

        jTextField1Genero.setColumns(10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6Genero)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1Genero, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4Año)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1Año, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3Director)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1Director, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1ID)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1ID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5Duracion)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1Duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                .addComponent(jButton1Agregar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2Titulo)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1Limpiar)))
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1ID)
                    .addComponent(jTextField1ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2Titulo)
                    .addComponent(jButton1Limpiar)
                    .addComponent(jTextField1Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3Director)
                    .addComponent(jTextField1Director, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4Año)
                    .addComponent(jTextField1Año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5Duracion)
                    .addComponent(jButton1Agregar)
                    .addComponent(jTextField1Duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6Genero)
                    .addComponent(jTextField1Genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1LimpiarActionPerformed
        jTextField1ID.setText("");
        jTextField1Titulo.setText("");
        jTextField1Director.setText("");
        jTextField1Año.setText("");
        jTextField1Duracion.setText("");
        jTextField1Genero.setText("");
    
    }//GEN-LAST:event_jButton1LimpiarActionPerformed

    private void jButton1AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1AgregarActionPerformed
        System.out.println("Se clickeo el boton");
        
        PeliculaDAO peliculaNueva;
        PeliculaController controller = new PeliculaController();
        
        if(jTextField1ID.getText().isEmpty() || jTextField1Titulo.getText().isEmpty() || jTextField1Director.getText().isEmpty() || jTextField1Año.getText().isEmpty() || jTextField1Duracion.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Favor rellenar todos los campos");
        }else{
            
             peliculaNueva = new PeliculaDAO();
            peliculaNueva.setId(Integer.parseInt(jTextField1ID.getText()));
            peliculaNueva.setTitulo(jTextField1Titulo.getText());
            peliculaNueva.setDirector(jTextField1Director.getText());
            peliculaNueva.setAño(Integer.parseInt(jTextField1Año.getText()));
            peliculaNueva.setDuracion(Integer.parseInt(jTextField1Duracion.getText()));
            peliculaNueva.setGenero(jTextField1Genero.getText());
            
            try {
                controller.agregarPeliculaController(peliculaNueva, this.conector.getConn());
            } catch (SQLException ex) {
                Logger.getLogger(AgregarPelicula.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
            
            
            
            
    }//GEN-LAST:event_jButton1AgregarActionPerformed
 
       
    /**
     * @param args the command line arguments
     */
     protected ConectorDB conector;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Agregar;
    private javax.swing.JButton jButton1Limpiar;
    private javax.swing.JLabel jLabel1ID;
    private javax.swing.JLabel jLabel2Titulo;
    private javax.swing.JLabel jLabel3Director;
    private javax.swing.JLabel jLabel4Año;
    private javax.swing.JLabel jLabel5Duracion;
    private javax.swing.JLabel jLabel6Genero;
    private javax.swing.JTextField jTextField1Año;
    private javax.swing.JTextField jTextField1Director;
    private javax.swing.JTextField jTextField1Duracion;
    private javax.swing.JTextField jTextField1Genero;
    private javax.swing.JTextField jTextField1ID;
    private javax.swing.JTextField jTextField1Titulo;
    // End of variables declaration//GEN-END:variables

}
